wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  volumes:
    - /opt/buildstack/apps/testapp/wordpress:/var/www/html
  ports:
    - 8080:80

wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: P@ssw0rd

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: P@ssw0rd
