wordpress:
  image: wordpress
  links:
    - db:mysql
  volumes:
    - /opt/buildstack/apps/testapp/html:/var/www/html
  ports:
    - 8080:80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
